set-option -g default-shell /bin/zsh
set-option -g history-limit 100000
set-option -g mouse on
bind-key -n S-left select-pane -L
bind-key -n "C-O" send-keys C-l \; send-keys -R \; clear-history
unbind-key M-w

bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"
unbind -T copy-mode-vi Enter
bind-key -T copy-mode-vi Enter send -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"


# rで設定読み込み
bind r source-file ~/.tmux.conf \; display "Config reloaded."

bind-key b split-window 'tmux lsw | peco | cut -d":" -f 1 | xargs tmux select-window -t'

# 垂直分割 + カレントディレクトリを引き継ぐ
bind "#" split-window -h -c "#{pane_current_path}"
# 水平分割 + カレントディレクトリを引き継ぐ
bind '"' split-window -v -c "#{pane_current_path}"


