add_newline = false
prompt_order = [
    "directory",
    "git_branch",
    "git_state",
#    "git_status", # line_break がない状態でこれを有効化するとバグる
    "package",
    "nodejs",
    "ruby",
    "rust",
    "python",
    "golang",
    "nix_shell",
    "cmd_duration",
    "jobs",
    "character"
]
