add_newline = false
prompt_order = [
    "directory",
    "git_branch",
    "git_state",
    "git_status",
    "package",
    "nodejs",
    "ruby",
    "rust",
    "python",
    "golang",
    "nix_shell",
    "cmd_duration",
    "jobs",
    "battery",
    "character"
]


[character]      # The name of the module we are confguring is "character"
symbol = "➜"

