[settings]
experimental = true
task_disable_paths = ["/Users/katsusuke/mnt"]

[tools]
java = "corretto-11.0.19.7.1"
python = "3.13.0"
ruby = "3.3.6"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:deno" = "latest"
"npm:@graphql-cli/init" = "latest"
"npm:eclint" = "latest"
node = "24"
"npm:@github/copilot-language-server" = "latest"
